# Generated by Django 5.1.1 on 2024-10-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='hairness',
            new_name='hairiness',
        ),
    ]
